# Generated by Django 4.0.6 on 2022-07-26 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establishment', '0002_remove_establishment_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('category', models.CharField(max_length=256)),
                ('director', models.CharField(max_length=256)),
                ('premiere_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('duration', models.PositiveSmallIntegerField()),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establishment.establishment')),
            ],
        ),
    ]
