# Generated by Django 4.0.6 on 2022-07-26 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='cinema',
            new_name='cinema_id',
        ),
    ]
