# Generated by Django 3.2.14 on 2022-07-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='movie',
            name='unique_title_director_category_combination',
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.UniqueConstraint(fields=('title', 'director', 'category', 'cinema'), name='unique_title_director_category_combination_cinema'),
        ),
    ]
