# Generated by Django 4.0.6 on 2022-07-26 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_rename_cinema_movie_cinema_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='cinema_id',
            new_name='cinema',
        ),
    ]
