# Generated by Django 4.0.6 on 2022-07-26 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='updated_at',
        ),
    ]
